version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  test:
    parameters:
      php_version:
        type: string
      composer_options:
        type: string
        default: ''
    docker:
      - image: circleci/php:<<parameters.php_version>>
      - image: mailhog/mailhog:v1.0.0
        command: "-api-bind-addr 0.0.0.0:9025 -ui-bind-addr 0.0.0.0:9025 -smtp-bind-addr 0.0.0.0:2025"
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-dependencies-<<parameters.php_version>>-<<parameters.composer_options>>-{{ checksum "composer.json" }}
      - run:
          command: COMPOSER_CACHE_DIR=composer-cache composer update --prefer-dist <<parameters.composer_options>>
          no_output_timeout: 30m
      - save_cache:
          paths: ['./composer-cache']
          key: composer-dependencies-<<parameters.php_version>>-<<parameters.composer_options>>-{{ checksum "composer.json" }}
      - run: make test

workflows:
  version: 2
  commit:
    jobs:
      - test:
          name: 'PHP 7.2'
          php_version: '7.2'
      - test:
          name: 'PHP 7.3'
          php_version: '7.3'
      - test:
          name: 'PHP 7.4'
          php_version: '7.4'
      - test:
          name: 'PHP 7.2 (lowest composer dependencies)'
          php_version: '7.2'
          composer_options: '--prefer-lowest'
      - test:
          name: 'PHP 7.3 (lowest composer dependencies)'
          php_version: '7.3'
          composer_options: '--prefer-lowest'
      - test:
          name: 'PHP 7.4 (lowest composer dependencies)'
          php_version: '7.4'
          composer_options: '--prefer-lowest'
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - test:
          name: 'PHP 7.2'
          php_version: '7.2'
      - test:
          name: 'PHP 7.3'
          php_version: '7.3'
      - test:
          name: 'PHP 7.4'
          php_version: '7.4'
      - test:
          name: 'PHP 7.2 (lowest composer dependencies)'
          php_version: '7.2'
          composer_options: '--prefer-lowest'
      - test:
          name: 'PHP 7.3 (lowest composer dependencies)'
          php_version: '7.3'
          composer_options: '--prefer-lowest'
      - test:
          name: 'PHP 7.4 (lowest composer dependencies)'
          php_version: '7.4'
          composer_options: '--prefer-lowest'
